name = "edbzn-blog-ideas"
main = "src/index.js"
compatibility_date = "2026-04-23"

[vars]
ALLOWED_ORIGIN = ["https://edbzn.dev", "http://localhost:*"]

[[kv_namespaces]]
binding = "edbzn-blog-ideas"
id = "59223b3111044b8fa5e3baa9e935dd25"

[observability]
enabled = true
